
# Site
name: 'Tech Women Norway'
description: 'Event to celebrate women working handson in tech'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
#disqus: 'demowebsite'
twitter: 
email: 'techwomen.no@gmail.com'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    patricia:
      name:           Patricia
      site:           https://patricia.no
      avatar:         assets/images/patricia.jpg
      bio:            "C++ Programmer and trainer"
      email:          psmaas@gmail.com
      twitter:        https://twitter.com/pati_gallardo


    winifred:
      name:           Winifred
      site:           https://winifredburton.com
      avatar:         assets/images/winifred.jpg
      bio:            "Writer and QA"
      email:
      twitter:        https://twitter.com/winnaburto
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: patricia
      avatar: /assets/images/patricia.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]